branch-defaults:
  default:
    environment: Udagramserver-env
    group_suffix: null

environment-defaults:
  Udagramserver-env:
    branch: null
    repository: null
global:
  application_name: udagram-server
  branch: null
  default_ec2_keyname: null
  default_platform: Node.js 14 running on 64bit Amazon Linux 2
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: null
  workspace_type: Application
deploy:
  artifact: www/Archive.zip
